name: generate-certificates

on: [push]

jobs:
  generate-certs:
    runs-on: macos-latest

    steps:
      # step 1: checkout repository
      - name: checkout repository
        uses: actions/checkout@v4

      # step 2: decode p12 certificate
      - name: decode p12 certificate
        run: |
          echo "${{ secrets.P12_BASE64 }}" | base64 --decode > Certificates.p12
          echo "decoded p12 certificate ✅"

      # step 3: decode provisioning profile
      - name: decode provisioning profile
        run: |
          echo "${{ secrets.MOBILEPROVISION_BASE64 }}" | base64 --decode > mobileprovision.mobileprovision
          echo "decoded provisioning profile ✅"

      # step 4: decode export options plist
      - name: decode export options plist
        run: |
          echo "${{ secrets.EXPORT_OPTIONS_BASE64 }}" | base64 --decode > ExportOptions.plist
          echo "decoded export options plist ✅"

      # step 5: re-encode files to base64
      - name: re-encode files to base64
        run: |
          base64 -i Certificates.p12 > cert_base64.txt
          base64 -i mobileprovision.mobileprovision > mobile_pp_base64.txt
          base64 -i ExportOptions.plist > export_opts_base64.txt

          echo "re-encoded files to base64 ✅"

      # step 6: upload base64 files as artifacts
      - name: upload base64-encoded files
        uses: actions/upload-artifact@v4
        with:
          name: base64-encoded-certificates
          path: |
            cert_base64.txt
            mobile_pp_base64.txt
            export_opts_base64.txt
